require 'rubygems/tasks/console'
require 'rubygems/tasks/build'
require 'rubygems/tasks/install'
require 'rubygems/tasks/scm'
require 'rubygems/tasks/scm'
require 'rubygems/tasks/push'
require 'rubygems/tasks/tasks'
